src/app/urls.py
import imp
from django.urls import path
from django.contrib.auth import views as auth_views

from app.views.index import index
from app.views.auth import register


app_name = 'app'


urlpatterns = [
    path('', index, name='index'),
    path('auth/login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(next_page='app:index'), name='logout'),
    path('auth/register/', register, name='register'),
]

src/core/urls.py
"""
Main urls
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

src/app/views/index.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoTemplate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>

<body>
    {% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    {% endif %}

    {% block nav %}
    {% endblock nav %}

    {% block content %}
    {% endblock content %}

    {% block script %}
    {% endblock script %}

</body>

</html>

src/app/templates/components/nav.html
{% block nav %}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarMain" class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'app:index' %}" class="navbar-item">Home</a>
            <a href="{% url 'app:index' %" class="navbar-item">Item</a>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="field is-grouped">
                    <div class="control">
                        {% if user.is_authenticated %}
                        <a href="{% url 'app:logout' %}" class="button is-primary">Logout</a>
                        {% else %}
                        <a href="{% url 'app:register' %}" class="button is-primary">Register</a>
                        <a href="{% url 'app:login' %}" class="button is-light">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>
{% endblock nav %}

{% block script %}
{% endblock script %}

src/app/templates/index.html
{% extends 'base.html' %}

{% block nav %}
{% include 'components/nav.html' %}
{% endblock nav %}

{% block content %}
{% endblock content %}

{% block script %}
{% endblock script %}